### ISSUE TITLE
yarn start报错

### ISSUE THREAD

**Issue by shinestmt** [i5sing/i5SING#14]
按Development步骤, yarn 再 yarn start, 报错如下:
```
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import { bootstrap } from "./app";
                                                                                                                                                                  ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
webpack built 5328886497a19cd88fb2 in 36846ms
```
系统: Win10
Node: v10.16.0
npm: 6.9.0
yarn: 1.13.0
tsc: 3.5.3

**Comment by shinestmt** [comment]
多执行了几次, 问题消失了
